# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FirebaseStarterApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseStarterApp

  pod 'FacebookCore', '~> 0.5.0'
  pod 'FacebookLogin', '~> 0.5.0'
  pod 'FacebookShare', '~> 0.5.0'

  pod 'Alamofire'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
